name: Send PR to another repository

on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  send-pr:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: onagano-rh/my-eap-webapp-config
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - run: |
          git config user.name "No Reply"
          git config user.email "noreply@example.com"
          git checkout -b work
          data > generated.txt
          git add .
          git commit -m "generated"
          git push -u origin work
